import json
import logging
import os
from typing import Dict, List, Optional
from dataclasses import dataclass, asdict
from pathlib import Path
import hashlib
import traceback
from collections import defaultdict

import fitz  # PyMuPDF
from groq import Groq
from dotenv import load_dotenv
from groq_extractor import KnowledgeGraphExtractor

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('kg_extractor.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

@dataclass
class TextChunk:
    """Data class to store chunk information"""
    id: str
    text: str
    page_num: int
    knowledge_graph: Dict  # Store chunk-specific knowledge graph
    summary: str = ""  # Summary generated by LLM
    key_points: List[str] = None  # Key points extracted by LLM
    
    def to_dict(self):
        return asdict(self)

class SimplifiedPDFProcessor:
    def __init__(self, 
                 chunk_size: int = 1000,
                 overlap: int = 50,
                 model: str = "llama3-70b-8192"):
        """
        Initialize the PDF processor
        
        :param chunk_size: Maximum characters per chunk
        :param overlap: Number of characters to overlap between chunks
        :param model: Groq model to use
        """
        self.chunk_size = chunk_size
        self.overlap = overlap
        self.kg_extractor = KnowledgeGraphExtractor(model=model)
        self.chunks = {}
        
        # Initialize Groq client
        load_dotenv()
        self.client = Groq(
            api_key=os.getenv("GROQ_API_KEY")
        )
        self.model = model

    def _generate_chunk_id(self, text: str, page_num: int) -> str:
        """Generate a unique ID for each chunk"""
        content = f"{text[:100]}_{page_num}"
        return hashlib.md5(content.encode()).hexdigest()

    def process_pdf(self, pdf_path: str) -> Dict:
        """Process PDF and create chunks with knowledge graphs"""
        logger.info(f"Starting to process PDF: {pdf_path}")
        
        pdf_path = Path(pdf_path).resolve()
        if not pdf_path.exists():
            raise FileNotFoundError(f"PDF file not found: {pdf_path}")
        
        try:
            doc = fitz.open(str(pdf_path))
            chunks = []
            
            for page_num, page in enumerate(doc):
                text = page.get_text("text")
                page_chunks = self._create_chunks(text, page_num)
                chunks.extend(page_chunks)
                
            # Process chunks with KnowledgeGraphExtractor
            for chunk in chunks:
                self._process_chunk(chunk)
                self.chunks[chunk.id] = chunk
                
            # Create final output with merged knowledge graph and chunk references
            result = self._create_final_output()
            return result
            
        except Exception as e:
            logger.error(f"Error processing PDF: {str(e)}")
            raise
        finally:
            if 'doc' in locals():
                doc.close()

    def _create_chunks(self, text: str, page_num: int) -> List[TextChunk]:
        """Create text chunks"""
        chunks = []
        start = 0
        
        while start < len(text):
            end = start + self.chunk_size
            chunk_text = text[start:end]
            
            chunk_id = self._generate_chunk_id(chunk_text, page_num)
            chunk = TextChunk(
                id=chunk_id,
                text=chunk_text,
                page_num=page_num,
                knowledge_graph={},
                key_points=[]
            )
            chunks.append(chunk)
            
            start = end - self.overlap
            
        return chunks

    def _generate_chunk_summary(self, text: str) -> Dict[str, any]:
        """Generate summary and key points using Groq LLM"""
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are an expert at summarizing text and extracting key information."
                    },
                    {
                        "role": "user",
                        "content": f"""Please analyze this text and provide:
                        1. A concise summary (2-3 sentences)
                        2. Key points as a list
                        
                        Text: {text}
                        
                        Provide your response in JSON format:
                        {{
                            "summary": "your summary here",
                            "key_points": ["point 1", "point 2", ...]
                        }}"""
                    }
                ],
                response_format={"type": "json_object"},
                temperature=0.3,
                max_tokens=512
            )
            
            return json.loads(response.choices[0].message.content)
        except Exception as e:
            logger.error(f"Error generating summary: {str(e)}")
            return {"summary": "", "key_points": []}

    def _process_chunk(self, chunk: TextChunk):
        """Process chunk using KnowledgeGraphExtractor and LLM"""
        try:
            # Extract knowledge graph
            chunk.knowledge_graph = self.kg_extractor.extract_knowledge_graph([chunk.text])
            
            # Generate summary and key points
            llm_output = self._generate_chunk_summary(chunk.text)
            chunk.summary = llm_output.get("summary", "")
            chunk.key_points = llm_output.get("key_points", [])
            
        except Exception as e:
            logger.error(f"Error processing chunk: {str(e)}")
            chunk.knowledge_graph = {"entities": [], "relationships": []}
            chunk.summary = ""
            chunk.key_points = []

    def _create_final_output(self) -> Dict:
        """Create final output with merged knowledge graph, summaries, and chunk references"""
        output = {
            "knowledge_graph": {
                "entities": [],
                "relationships": []
            },
            "chunks": {},
            "document_summary": {
                "overall_summary": "",
                "key_themes": []
            }
        }
        
        entity_map = {}
        relationship_map = {}
        entity_chunks = defaultdict(set)
        
        # Process each chunk
        all_summaries = []
        for chunk_id, chunk in self.chunks.items():
            # Store enhanced chunk info
            output["chunks"][chunk_id] = {
                "text": chunk.text,
                "page_num": chunk.page_num,
                "summary": chunk.summary,
                "key_points": chunk.key_points
            }
            all_summaries.append(chunk.summary)
            
            # Process entities
            for entity in chunk.knowledge_graph.get("entities", []):
                entity_id = entity.get("id")
                if entity_id not in entity_map:
                    entity_map[entity_id] = {
                        "id": entity_id,
                        "name": entity.get("name", ""),
                        "type": entity.get("type", "UNKNOWN"),
                        "aliases": entity.get("aliases", []),
                        "description": entity.get("description", ""),
                        "attributes": entity.get("attributes", {}),
                        "chunk_refs": []
                    }
                entity_chunks[entity_id].add(chunk_id)
                
            # Process relationships
            for rel in chunk.knowledge_graph.get("relationships", []):
                rel_id = rel.get("id")
                if rel_id not in relationship_map:
                    relationship_map[rel_id] = {
                        "id": rel_id,
                        "source_id": rel.get("source_id"),
                        "target_id": rel.get("target_id"),
                        "types": rel.get("types", []),
                        "strength": rel.get("strength", 0.5),
                        "description": rel.get("description", ""),
                        "chunk_refs": []
                    }
                relationship_map[rel_id]["chunk_refs"].append(chunk_id)
        
        # Update entity chunk references
        for entity_id, chunks in entity_chunks.items():
            if entity_id in entity_map:
                entity_map[entity_id]["chunk_refs"] = list(chunks)
        
        # Generate overall document summary
        try:
            all_summaries_text = "\n".join(all_summaries)
            doc_summary = self._generate_document_summary(all_summaries_text)
            output["document_summary"] = doc_summary
        except Exception as e:
            logger.error(f"Error generating document summary: {str(e)}")
        
        # Add to final output
        output["knowledge_graph"]["entities"] = list(entity_map.values())
        output["knowledge_graph"]["relationships"] = list(relationship_map.values())
        
        return output

    def _generate_document_summary(self, summaries_text: str) -> Dict[str, any]:
        """Generate overall document summary from chunk summaries"""
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are an expert at synthesizing information and identifying key themes."
                    },
                    {
                        "role": "user",
                        "content": f"""Based on these chunk summaries, provide:
                        1. An overall document summary (3-4 sentences)
                        2. Key themes or topics found throughout the document
                        
                        Chunk Summaries:
                        {summaries_text}
                        
                        Provide your response in JSON format:
                        {{
                            "overall_summary": "your summary here",
                            "key_themes": ["theme 1", "theme 2", ...]
                        }}"""
                    }
                ],
                response_format={"type": "json_object"},
                temperature=0.3,
                max_tokens=1024
            )
            
            return json.loads(response.choices[0].message.content)
        except Exception as e:
            logger.error(f"Error generating document summary: {str(e)}")
            return {
                "overall_summary": "",
                "key_themes": []
            }

def main():
    try:
        processor = SimplifiedPDFProcessor()
        pdf_path = input("Enter the path to your PDF file: ").strip()
        
        # Process PDF and get output with chunk references
        result = processor.process_pdf(pdf_path)
        
        # Save results
        output_dir = "output"
        os.makedirs(output_dir, exist_ok=True)
        
        # Save complete output
        with open(os.path.join(output_dir, "pdf_knowledge_graph.json"), 'w') as f:
            json.dump(result, f, indent=2)
        
        print("\nExtraction Summary:")
        print(f"Total chunks created: {len(result['chunks'])}")
        print(f"Total unique entities: {len(result['knowledge_graph']['entities'])}")
        print(f"Total relationships: {len(result['knowledge_graph']['relationships'])}")
        print("\nDocument Summary:")
        print(result["document_summary"]["overall_summary"])
        print("\nKey Themes:")
        for theme in result["document_summary"]["key_themes"]:
            print(f"- {theme}")
        
    except Exception as e:
        logger.error(f"Error in main execution: {str(e)}\n{traceback.format_exc()}")
        print(f"An error occurred. Check the log file for details: {str(e)}")
        return 1
    
    return 0

if __name__ == "__main__":
    exit(main())